DIGITAL_HALF_0:
  ADC_TH: 0
  BYPASSCH0: 0
  BYPASSCH17: 0
  BYPASSCH35: 0
  CMDSELEDGE: 1
  IDLEFRAME: 214748364
  L1OFFSET: 8
  MULTFACTOR: 25
  SELRAWDATA: 1
  SELTC4: 1
  TOT_P0: 0
  TOT_P1: 0
  TOT_P2: 0
  TOT_P3: 0
  TOT_TH0: 0
  TOT_TH1: 0
  TOT_TH2: 0
  TOT_TH3: 0
DIGITAL_HALF_1:
  ADC_TH: 0
  BYPASSCH0: 0
  BYPASSCH17: 0
  BYPASSCH35: 0
  CMDSELEDGE: 1
  IDLEFRAME: 214748364
  L1OFFSET: 8
  MULTFACTOR: 25
  SELRAWDATA: 1
  SELTC4: 1
  TOT_P0: 0
  TOT_P1: 0
  TOT_P2: 0
  TOT_P3: 0
  TOT_TH0: 0
  TOT_TH1: 0
  TOT_TH2: 0
  TOT_TH3: 0
GLOBAL_ANALOG_0:
  CLR_ADC: 0
  CLR_SHAPERTAIL: 0
  DACB_VBI_PA: 31
  DACB_VB_CONV: 51
  DELAY40: 5
  DELAY65: 2
  DELAY87: 2
  DELAY9: 2
  EN_HYST_TOT: 0
  GAIN_CONV: 4
  IBI_INV: 0
  IBI_INV_BUF: 3
  IBI_NOINV: 0
  IBI_NOINV_BUF: 3
  IBI_SK: 0
  IBO_INV: 10
  IBO_INV_BUF: 38
  IBO_NOINV: 10
  IBO_NOINV_BUF: 38
  IBO_SK: 10
  ON_CONV: 1
  ON_DAC_TRIM: 1
  ON_INPUT_DAC: 1
  ON_PA: 1
  ON_REF_ADC: 1
  ON_RTR: 1
  ON_TOA: 1
  ON_TOT: 1
  POL_ADC: 1
  REF_ADC: 0
  SELEXTADC: 0
  SELRISINGEDGE: 1
  SW_CD: 7
  SW_CF: 10
  SW_CF_COMP: 10
  SW_RF: 5
  SW_SUPER_CONV: 1
  S_INV: 2
  S_INV_BUF: 6
  S_NOINV: 2
  S_NOINV_BUF: 6
  S_SK: 2
GLOBAL_ANALOG_1:
  CLR_ADC: 0
  CLR_SHAPERTAIL: 0
  DACB_VBI_PA: 31
  DACB_VB_CONV: 51
  DELAY40: 5
  DELAY65: 2
  DELAY87: 2
  DELAY9: 2
  EN_HYST_TOT: 0
  GAIN_CONV: 4
  IBI_INV: 0
  IBI_INV_BUF: 3
  IBI_NOINV: 0
  IBI_NOINV_BUF: 3
  IBI_SK: 0
  IBO_INV: 10
  IBO_INV_BUF: 38
  IBO_NOINV: 10
  IBO_NOINV_BUF: 38
  IBO_SK: 10
  ON_CONV: 1
  ON_DAC_TRIM: 1
  ON_INPUT_DAC: 1
  ON_PA: 1
  ON_REF_ADC: 1
  ON_RTR: 1
  ON_TOA: 1
  ON_TOT: 1
  POL_ADC: 1
  REF_ADC: 0
  SELEXTADC: 0
  SELRISINGEDGE: 1
  SW_CD: 7
  SW_CF: 10
  SW_CF_COMP: 10
  SW_RF: 5
  SW_SUPER_CONV: 1
  S_INV: 2
  S_INV_BUF: 6
  S_NOINV: 2
  S_NOINV_BUF: 6
  S_SK: 2
REFERENCE_VOLTAGE_0:
  CALIB_DAC: 0
  EXTCTEST: 0
  INTCTEST: 0
  INV_VREF: 384
  NOINV_VREF: 316
  ON_DAC: 1
  PROBE_DC: 0
  PROBE_VREF_PA: 0
  PROBE_VREF_TIME: 0
  REFI: 3
  TOA_VREF: 112
  TOT_VREF: 432
  VBG_1V: 7
REFERENCE_VOLTAGE_1:
  CALIB_DAC: 0
  EXTCTEST: 0
  INTCTEST: 0
  INV_VREF: 384
  NOINV_VREF: 316
  ON_DAC: 1
  PROBE_DC: 0
  PROBE_VREF_PA: 0
  PROBE_VREF_TIME: 0
  REFI: 3
  TOA_VREF: 112
  TOT_VREF: 432
  VBG_1V: 7
TOP:
  BIAS_I_PLL_D: 63
  DIV_PLL: 0
  EN_HIGH_CAPA: 1
  EN_LOCK_CONTROL: 0
  EN_PHASESHIFT: 1
  EN_PLL: 1
  EN_PLL_EXT: 0
  EN_REF_BG: 1
  ERROR_LIMIT_SC: 0
  ET_AMPLITUDE: 3
  ET_PRE_PHASE: 0
  ET_PRE_SCALE: 0
  FOLLOWER_PLL_EN: 1
  ORBITSYNC_SC: 0
  PHASE: 0
  PLLLOCKEDSC: 1
  PLL_PROBE_AMPLITUDE: 3
  PLL_PROBE_PRE_PHASE: 0
  PLL_PROBE_PRE_SCALE: 0
  SEL_40M_EXT: 0
  SEL_L1_FCMD: 1
  SEL_ORBITSYNC_FCMD: 1
  SEL_PLL_LOCKED: 1
  SEL_RESYNC_FCMD: 1
  SEL_STROBE_FCMD: 1
  VOUT_INIT_EN: 0
  VOUT_INIT_EXT_D: 0
  VOUT_INIT_EXT_EN: 0
