Global_Analog_*:
  ON_dac_trim: 1
  ON_input_dac: 1
  ON_conv: 1
  ON_pa: 1
  Gain_conv: 0b0100
  ON_rtr: 1
  Sw_super_conv: 1
  Dacb_vb_conv: 51
  ON_toa: 1
  ON_tot: 1
  Dacb_vbi_pa: 31
  Ibi_sk: 0
  Ibo_sk: 10
  Ibi_inv: 0
  Ibo_inv: 10
  Ibi_noinv: 0
  Ibo_noinv: 10
  Ibi_inv_buf: 3
  Ibo_inv_buf: 38
  Ibi_noinv_buf: 3
  Ibo_noinv_buf: 38
  Sw_cd: 0b100
  En_hyst_tot: 0
  Sw_Cf_comp: 0b1010
  Sw_Cf: 0b1010
  Sw_Rf: 0b0001
  Clr_ShaperTail: 0
  SelRisingEdge: 1
  SelExtADC: 0
  Clr_ADC: 0
  S_sk: 0b010
  S_inv: 0b010
  S_noinv: 0b010
  S_inv_buf: 0b110
  S_noinv_buf: 0b110
  Ref_adc: 0
  Delay40: 0b010
  Delay65: 0b010
  ON_ref_adc: 1
  Pol_adc: 1
  Delay87: 0b010
  Delay9: 0b010

Reference_Voltage_*:
  Probe_vref_pa: 0
  Probe_vref_time: 0
  Refi: 0b11
  Vbg_1v: 0b100
  ON_dac: 1
  Tot_vref: 0b0101110010
  Toa_vref: 0b0001110000
  Inv_vref: 0b0101110010
  Noinv_vref: 0b0011111010
  Calib_dac: 0
  IntCtest: 0
  ExtCtest: 0

Master_TDC_*:
  GLOBAL_TA_SELECT_GAIN_TOA: 3
  GLOBAL_TA_SELECT_GAIN_TOT: 3
  GLOBAL_MODE_NO_TOT_SUB: 0
  GLOBAL_LATENCY_TIME: 10
  GLOBAL_MODE_FTDC_TOA_S0: 0
  GLOBAL_MODE_FTDC_TOA_S1: 1
  GLOBAL_SEU_TIME_OUT: 1
  BIAS_FOLLOWER_CAL_P_D: 0
  BIAS_FOLLOWER_CAL_P_EN: 0
  INV_FRONT_40MHZ: 0
  START_COUNTER: 1
  CALIB_CHANNEL_DLL: 0
  VD_CTDC_P_D: 0
  VD_CTDC_P_DAC_EN: 0
  EN_MASTER_CTDC_VOUT_INIT: 0
  EN_MASTER_CTDC_DLL: 1
  BIAS_CAL_DAC_CTDC_P_D: 0
  CTDC_CALIB_FREQUENCY: 2
  GLOBAL_MODE_TOA_DIRECT_OUTPUT: 0
  BIAS_I_CTDC_D: 24
  FOLLOWER_CTDC_EN: 1
  GLOBAL_EN_BUFFER_CTDC: 0
  VD_CTDC_N_FORCE_MAX: 1
  VD_CTDC_N_D: 0
  VD_CTDC_N_DAC_EN: 0
  CTRL_IN_REF_CTDC_P_D: 0
  CTRL_IN_REF_CTDC_P_EN: 0
  CTRL_IN_SIG_CTDC_P_D: 0
  CTRL_IN_SIG_CTDC_P_EN: 0
  GLOBAL_INIT_DAC_B_CTDC: 0
  BIAS_CAL_DAC_CTDC_P_EN: 1
  VD_FTDC_P_D: 0
  VD_FTDC_P_DAC_EN: 0
  EN_MASTER_FTDC_VOUT_INIT: 0
  EN_MASTER_FTDC_DLL: 1
  BIAS_CAL_DAC_FTDC_P_D: 0
  FTDC_CALIB_FREQUENCY: 2
  EN_REF_BG: 1
  BIAS_I_FTDC_D: 24
  FOLLOWER_FTDC_EN: 1
  GLOBAL_EN_BUFFER_FTDC: 0
  VD_FTDC_N_FORCE_MAX: 1
  VD_FTDC_N_D: 0
  VD_FTDC_N_DAC_EN: 0
  CTRL_IN_SIG_FTDC_P_D: 0
  CTRL_IN_SIG_FTDC_P_EN: 0
  GLOBAL_INIT_DAC_B_FTDC: 0
  BIAS_CAL_DAC_FTDC_P_EN: 0
  CTRL_IN_REF_FTDC_P_D: 0
  CTRL_IN_REF_FTDC_P_EN: 0
  GLOBAL_DISABLE_TOT_LIMIT: 0
  GLOBAL_FORCE_EN_CLK: 0
  GLOBAL_FORCE_EN_OUTPUT_DATA: 0
  GLOBAL_FORCE_EN_TOT: 0
